<?php

declare(strict_types=1);

namespace ZabalaGailetak\HrPortal\Controllers\Web;

use ZabalaGailetak\HrPortal\Http\Request;
use ZabalaGailetak\HrPortal\Http\Response;
use ZabalaGailetak\HrPortal\Database\Database;
use ZabalaGailetak\HrPortal\Services\VacationService;
use PDO;

class WebVacationController
{
    private Database $db;
    private VacationService $vacationService;

    public function __construct(Database $db, VacationService $vacationService)
    {
        $this->db = $db;
        $this->vacationService = $vacationService;
    }

    public function index(Request $request): Response
    {
        $this->requireAuth();
        $employeeId = $this->getCurrentEmployeeId();

        if (!$employeeId) {
             return Response::view('vacations/index', ['error' => 'No tienes perfil de empleado asociado.']);
        }

        $year = (int)date('Y');
        $balance = $this->vacationService->getBalance($employeeId, $year) 
                   ?? $this->vacationService->initializeBalance($employeeId, $year);
        
        $requests = $this->vacationService->getEmployeeRequests($employeeId, $year);

        return Response::view('vacations/index', [
            'balance' => $balance,
            'requests' => $requests,
            'year' => $year
        ]);
    }

    public function requestForm(Request $request): Response
    {
        $this->requireAuth();
        return Response::view('vacations/create');
    }

    public function create(Request $request): Response
    {
        $this->requireAuth();
        $data = $request->getParsedBody();
        $employeeId = $this->getCurrentEmployeeId();

        if (!$employeeId) {
             return Response::redirect('/vacations');
        }

        try {
            $this->vacationService->createRequest(
                $employeeId,
                $data['start_date'],
                $data['end_date'],
                $data['notes'] ?? null
            );
            // Flash message logic would go here
        } catch (\Exception $e) {
            // Flash error
        }

        return Response::redirect('/vacations');
    }

    private function requireAuth(): void
    {
        if (!isset($_SESSION['user_id'])) {
            header('Location: /login');
            exit;
        }
    }

    private function getCurrentEmployeeId(): ?int
    {
        // Simplistic: Assuming SESSION stores user_id, fetch employee_id
        // Ideally SESSION should store employee_id on login
        // But let's fetch it if not present
        if (isset($_SESSION['employee_id'])) {
            // Check if string UUID or int ID. PostgreSQL uses UUID, MySQL migration uses UUID generated by PHP.
            // Wait, migration kept UUID column type? No, converted to VARCHAR(36) in DB.
            // But Service expects int for employeeId? 
            // Looking at VacationService.php: public function getBalance(int $employeeId, int $year)
            // It expects INT. But DB uses UUID (VARCHAR 36).
            // Migration script changed SERIAL to INT AUTO_INCREMENT for MySQL.
            // Ah, wait. Did I convert IDs to INT in migration?
            // "SERIAL PRIMARY KEY" -> "INT AUTO_INCREMENT PRIMARY KEY" in migration script.
            // So IDs are INTs in MySQL.
            return (int)$_SESSION['employee_id'];
        }

        $stmt = $this->db->prepare("SELECT id FROM employees WHERE user_id = :user_id");
        $stmt->execute(['user_id' => $_SESSION['user_id']]);
        $id = $stmt->fetchColumn();
        
        if ($id) {
            $_SESSION['employee_id'] = $id;
            return (int)$id;
        }
        return null;
    }
}
